"""Adicionar coluna 'finalizada' à tabela Consulta

Revision ID: 358339f2a442
Revises: 38e9c9eec92c
Create Date: 2024-02-19 16:02:08.925926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358339f2a442'
down_revision = '38e9c9eec92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_column('finalizada')

    # ### end Alembic commands ###
