"""Adicionar coluna 'feita' à tabela Consulta

Revision ID: 38e9c9eec92c
Revises: e38ab8988a42
Create Date: 2023-12-17 19:22:48.637502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e9c9eec92c'
down_revision = 'e38ab8988a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feita', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_column('feita')

    op.create_table('notificacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('psicologo_id', sa.INTEGER(), nullable=False),
    sa.Column('consulta_id', sa.INTEGER(), nullable=False),
    sa.Column('lida', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
